

words = {
    "on": "is",
    "ja": "and",
    "ei": "no",
    "kyllä": "yes",
    "mikä": "what",
    "missä": "where",
    "kuinka": "how",
    "se": "it",
    "minä": "I",
    "sinä": "you",
    "me": "we",
    "he": "they",
    "hän": "he/she",
    "olisi": "would be",
    "täällä": "here",
    "tuolla": "there",
    "nyt": "now",
    "kaikki": "all",
    "tiedän": "I know",
    "rakastaa": "to love",
    "tehdä": "to do",
    "puhua": "to speak",
    "nähdä": "to see",
    "kuulla": "to hear",
    "täytyä": "to have to",
    "haluta": "to want",
    "mennä": "to go",
    "tulla": "to come",
    "voida": "to be able to",
    "antaa": "to give",
    "ottaa": "to take",
    "metä": "forest",
    "koti": "home",
    "työ": "work",
    "opiskelija": "student",
    "ystävä": "friend",
    "perhe": "family",
    "ruoka": "food",
    "vesi": "water",
    "päivä": "day",
    "yö": "night",
    "aika": "time",
    "vuosi": "year",
    "sana": "word",
    "kirja": "book",
    "kaupunki": "city",
    "autus": "car",
    "koulutus": "education",
    "asio": "thing",
    "vähän": "a little",
    "paljon": "a lot",
    "vielä": "still",
    "aina": "always",
    "jos": "if",
    "kuin": "than",
    "mutta": "but",
    "koska": "because",
    "kuitenkin": "however",
    "vaikka": "although",
    "niin": "so",
    "meidän": "our",
    "teidän": "your",
    "heidän": "their",
    "itse": "oneself",
    "kanssa": "with",
    "ilman": "without",
    "mielestä": "according to",
    "aikana": "during",
    "yli": "over",
    "alhaalla": "below",
    "yhdessä": "together",
    "erityisesti": "especially",
    "joten": "so",
    "tässä": "here",
    "tuossa": "there",
    "sitten": "then",
    "kotiin": "home (to)",
    "edessä": "in front of",
    "takana": "behind",
    "kanssa": "with",
    "ongelma": "problem",
    "ratkaisu": "solution",
    "idea": "idea",
    "liike": "movement",
    "tapahtuma": "event",
    "valinta": "choice",
    "vallita": "to dominate",
    "kysymys": "question",
    "toivon": "I hope",
    "tiedätte": "you know"
}